pipeline {
  agent any

  environment {
    SERVICE_NAME = "auth-service"
    DOCKER_IMAGE = "03atharva/${env.SERVICE_NAME}:latest"
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Atharva-04/CI-CD-Pipeline.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        dir("microservices/${env.SERVICE_NAME}") {
          script {
            bat "docker build -t %DOCKER_IMAGE% ."
          }
        }
      }
    }

    stage('Run Tests') {
      steps {
        dir("microservices/${env.SERVICE_NAME}") {
          bat 'npm install'
          bat 'npm test'
        }
      }
    }

    stage('Push Image') {
      when {
        branch 'main'
      }
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          bat '''
            echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
            docker push %DOCKER_IMAGE%
          '''
        }
      }
    }
  }
}
